### PR TITLE
Add tests for in_addr (see in.h)

### PR DESCRIPTION
**Pull request by nbrachet**
Allows to check if a network interface didn't get an IP address for instance:
```
try NetworkInterface.all
    .filter { $0.up             // Only active network interfaces…
              && !$0.loopback } // Ignoring loopback interfaces…
    .compactMap(\.address)      // That have addresses and…
    .filter(\.isIPv4)           // Use IPv4.
    .filter { !$0.inLinkLocalNet } // Not in link local network
```

### CODE REVIEW

**Comment by wadetregaskis** [comment]
Thanks for these additions!

There's a few changes I'd like to make, which I'm happy to do myself after taking this patch, but I'd like your thoughts & ideas first.

### Generic functionality that might not have implementations for all families

Some of these properties should in principle apply to any address type (e.g. `isLoopback` - I think?) and so _do_ make sense on the general `NetworkAddress` type, but I don't even know how to implement them for most address families.  So I think those properties should return `Bool?` to better convey the unsupported cases.  What do you think?

### Family-specific functionality

I think it'd be cleaner to have IPv4-specific things delineated in some clear way, so that it's not possible to e.g. accidentally use `isClassANet` on a link-layer address, where the property doesn't make sense.

An obvious way to do this would be to use subclassing, where only the `IPv4Address` subclass has properties like `isClassANet`.  API-wise that seems quite elegant, but that feels like it'd be a bit heavier at runtime (reference counting cost concerns) and overkill in that respect for what's typically just eight to thirty bytes (IPv4, IPv6, and link-layer addresses - the most common three families in use).  It also seems to go against [Apple's guidance](https://developer.apple.com/documentation/swift/choosing-between-structures-and-classes).

So then I thought about following Apple's prescribed approach, using protocols.  So there'd be a separate `IPv4Address` struct which would have these IPv4-specific attributes.  `NetworkAddress` could become a protocol so that generic functionality (e.g. CustomStringConvertible) could be shared amongst all address structs - since they'd still all have the same sockaddr_* data at their heart - and what's currently called `NetworkAddress` could become `AnyNetworkAddress`, with a `var IPv4: IPv4Address` property for (essentially) downcasting.

But that feels icky, like reimplementing classes with structs - which is what `sockaddr` et al do, in the C system library, and frankly it's a pain in the bum to actually use.  Granted Swift's version of that is significantly more elegant, but still.

But then I thought, what if there's additional structs (for each address family) but they're more like 'views' that expose _additional_ methods & properties, but are supplemental to the core `NetworkAddress` struct, not replacements.  So e.g. `IPv4View` (and `var IPv4: IPv4View?` on `NetworkAddress`) that has IPv4-specific stuff in it, and its only data would be the actual UInt32 (or similar) address, so it'd be super lightweight still.  As a special-case - nominally generic functionality would remain on `NetworkAddress` - it could implement `CustomStringConvertible`, since that `description` method is so helpful and the generic implementation on `NetworkAddress` could utilise that implementation rather than inlining it for every supported address family.

I think that's the best idea so far, but what do you think?

**Comment by wadetregaskis** [comment]
Oh, and I should have clarified that just keeping everything in a flat `NetworkAddress`, but making all the properties optional, seems like a worse approach since then you're forced to deal with optionality _everywhere_.  I prefer some way to say "is this an IPv4 address?" just once, and then not have to unwrap further optionals for IPv4-specific functionality.

**Comment by nbrachet** [comment]
Let me think about that...

**Comment by nbrachet** [comment]
Agreed on that point. Kinda of why I didn't make all those properties
optional.

**Comment by nbrachet** [comment]
I agree: *views* to encapsulate family's specific methods and properties
would be the most elegant way.
Excuse my poor knowledge of Swift but how do you implement views? Just
struct with a copy of the underlying address?

One hiccup is for predicates that make sense for multiple families, like
isLoopback (which does make sense for IPv4 and IPv6). It would be awkward for
the client to have to create 2 views. Although I suppose those predicates
could still be present in the core NetworkAddress.

Have you thought about using free functions? Effectively exposing
IPv4Address (and IPv6Address and...) and defining a isLoopback function
(and isLinkLocal, and ...)?

**Comment by wadetregaskis** [comment]
> I agree: *views* to encapsulate family's specific methods and properties would be the most elegant way. Excuse my poor knowledge of Swift but how do you implement views? Just struct with a copy of the underlying address?

Yep, basically.  One could copy the whole underlying data, but I think here it'd make more sense to just extract the address itself - e.g. that one UInt32 for IPv4 - since that's all the view needs, and it has to be extracted somewhere so might as well do it just once up front.

> One hiccup is for predicates that make sense for multiple families, like isLoopback (which does make sense for IPv4 and IPv6). It would be awkward for the client to have to create 2 views. Although I suppose those predicates could still be present in the core NetworkAddress.

Yeah, that's what I'm thinking.  It's a judgement call for things which aren't truly universal to all address families, but realistically anything which covers IPv4, IPv6, and link-layer addresses is probably good enough since those three cover 99% of use cases, I expect.

> Have you thought about using free functions? Effectively exposing IPv4Address (and IPv6Address and...) and defining a isLoopback function (and isLinkLocal, and ...)?

As in?:

```swift
struct NetworkAddress {
    …
    var IPv4Address: UInt32
}

func isLoopback(address: UInt32) -> Bool {
    …
}
```

Or do you mean still having IPv4Address as a struct…?

Either way, though, I'm not sure what the advantage would be.  The disadvantage is the usual for free-floating 'globals' - discovery through auto-completion would be hampered (and global namespace pollution).

**Comment by nbrachet** [comment]
On Sun, Apr 30, 2023 at 11:27 AM Wade Tregaskis ***@***.***>
wrote:

> I agree: *views* to encapsulate family's specific methods and properties
> would be the most elegant way. Excuse my poor knowledge of Swift but how do
> you implement views? Just struct with a copy of the underlying address?
>
> Yep, basically. One could copy the whole underlying data, but I think here
> it'd make more sense to just extra the address itself - e.g. that one
> UInt32 for IPv4 - since that's all the view needs, and it has to be
> extracted somewhere so might as well do it just once up front.
>
FWIW I like this approach. Seems the most elegant.

> One hiccup is for predicates that make sense for multiple families, like
> isLoopback (which does make sense for IPv4 and IPv6). It would be awkward
> for the client to have to create 2 views. Although I suppose those
> predicates could still be present in the core NetworkAddress.
>
> Yeah, that's what I'm thinking. It's a judgement call for things which
> aren't truly universal to all address families, but realistically anything
> which covers IPv4, IPv6, and link-layer addresses is probably good enough
> since those three cover 99% of use cases, I expect.
>
> Have you thought about using free functions? Effectively exposing
> IPv4Address (and IPv6Address and...) and defining a isLoopback function
> (and isLinkLocal, and ...)?
>
> As in?:
>
> struct NetworkAddress {
>     …
>     var IPv4Address: UInt32
> }
> func isLoopback(address: UInt32) -> Bool {
>     …
> }
>
> Or do you mean still having IPv4Address as a struct…?
>
> Either way, though, I'm not sure what the advantage would be. The
> disadvantage is the usual for free-floating 'globals' - discovery through
> auto-completion would be hampered (and global namespace pollution).
>
I was thinking of a way to avoid having to write (as a client):

NetworkInterface.all.filter { $0.IPv4.isLoopback || $0.IPv6.isLoopback }
but it is probably not worth it.

**Pull request merged**
